import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (

    <div>
      <Head>
        <title>Thusala's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-zinc-950 to-slate-900 px-10 md:px-20 lg:px-40">        
        <section className="min-h-screen">
          <nav className = "py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Thusala's Portfolio</h1>
            <ul className="flex items-center">
              {/* <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li> */}
              <li><a href="#" className="bg-gradient-to-r from-teal-500 text- to-teal-600 text-white px-4 py-2 border-none rounded-md ml-8">Resume</a></li>
            </ul>
          </nav>

          <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-emerald-600 font-medium md:text-6xl">Thusala Piyarisi</h2>
          <h3 className="text-2xl py-2 md:text-3xl ">FullStack Developer | Designer </h3>
          <p className="text-md py-5 text-gray-500 md:text-xl max-w-lg mx-auto">I offer full-stack development, design services, and digital consultation to help businesses enhance their online presence </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/thusalapov"><AiFillTwitterCircle /></a>
              <a href="https://www.linkedin.com/in/thusala-piyarisi-566091243/"><AiFillLinkedin /></a>
              <a href="https://github.com/thusalapi"><AiFillGithub /></a>
          </div>

          <div className="relative bg-gradient-to-b from-emerald-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div className="text-center p-10">
            <h3 className="text-3xl py-1 dark:text-white ">Profile</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 mt-10">
            I've always been drawn to the idea of creating comprehensive solutions 
            that encompass both the <span className="text-teal-500">front-end and back-end</span> aspects of software development. 
            Full Stack Engineering allows me to tackle a wide range of challenges, 
            from designing user interfaces to optimizing server performance. 
            It's incredibly rewarding to see a project come to life from start to finish, 
            and <span className="text-teal-500">the versatility of Full Stack Engineering </span>enables me to work on a variety of projects across different industries.
            </p>

          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="text-center p-10">
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 mt-10">
            Throughout my career as a freelance designer and developer, I've worked remotely with agencies, provided consultation for startups, and collaborated on digital products for various sectors. My services span across brand design, programming, and digital consultation, tailored to drive business growth and consumer engagement.
            </p>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );

  
}
